apiVersion: v1
kind: BuildConfig
metadata:
  name: gsi-enablement-one.inventory-svc-stock
  labels:
    app: inventory-svc-stock
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/gsi-enablement-one/inventory-svc-stock.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: inventory
        - name: BRANCH
          value: master
